# Generated by Django 5.1.3 on 2024-12-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=100)),
                ('summoner_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('kda', models.CharField(max_length=10)),
                ('farm', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.player')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('playstyle_tags', models.JSONField()),
                ('role', models.CharField(db_index=True, max_length=20)),
                ('difficulty', models.IntegerField()),
                ('similar_champions', models.ManyToManyField(blank=True, to='analysis.champion')),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'role'], name='analysis_ch_name_f016a1_idx')],
            },
        ),
    ]
